config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :pages
 resources :links
 resources :comments
 resources :votes
 root :to => "pages#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
belongs_to :user
has_many :comments 
has_many :votes

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :links
	has_many :comments
	has_many :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	validates :user_id, uniqueness: { scope: :link_id}
	belongs_to :user
	belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!	
	def create
		@comment = current_user.comments.create(comment_params)
		redirect_to :back
	end 

private
	def comment_params
		params.require(:comment).permit(:message, :link_id)
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
  end

  def new
  	@link = Link.new
  end

  def create
  	@link = Link.new(link_params)
  	if @link.save
  		#render "new"
  		redirect_to "/"
  	else
  		#this line overrides rendering behavior
  		render "new"
  end
end
private

def link_params
	params.require(:link).permit(:title,:url)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@links = Link.all
		@links = Link.paginate(:page => params[:page], :per_page => 5)
		Vote.find_each {|vote| vote.destroy unless vote.valid? }
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!
  def create
    @vote = Vote.where(link_id:params[:vote][:link_id], user_id: current_user.id).first
    if @vote
      @vote.up = params[:vote][:up]
      @vote.save
    else
      @vote = current_user.votes.create(vote_params)
    end
    #@vote = current_user.votes.create(vote_params)
    #puts "======================"
    #puts @vote.errors.inspect
    redirect_to :back
  end

  private
    def vote_params
      params.require(:vote).permit(:up, :link_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div data-alert="alert" class="alert alert-<%= level %> fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>
<%= yield %>

</body>
</html>
<%# user is logged in, show log out link %>
<% if current_user.present? %>
	<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<%# user is not logged in, show signup and login link %>
<% else %>
	<%= link_to 'Sign in', new_user_session_path %>
	<%= link_to 'Register Now!', new_user_registration_path %>
<% end %>

app/views/links/new.html.erb
 <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/show.html.erb
<h2>Comments:<h2>
<div>
  <% @link.comments.each do |comment| %>
    <p><%= comment.message %></p>
  <% end %>
</div>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :link_id, :value => @link.id %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :placeholder => "Add a comment" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/index.html.erb
<h2>I AMA Wannabe Reddit Homepage</h2>
<%= link_to "Add a link", new_link_path %>
<ul>
	<% @links.each do |link| %>
		<li><%= link_to link.title, link.url %></li>
			<%= link_to "comments", link %>
			<% if current_user && current_user.votes.where(:link_id => link.id, :up => false).present? %> 
	        *
  			<% else %>
    		<%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
 			<% end %>
			<% if current_user && current_user.votes.where(:link_id => link.id, :up => true).present? %>
    		*
  			<% else %>
    		<%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
  			<% end %>
			Votes: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>

	<% end %>
</ul>
 <%= will_paginate @links %>